### PR TITLE
Add default React app

### PR DESCRIPTION
**Pull request by raq929**
Setup to run in a development mode with hot reload and also to be served via the flask application

Please review by pulling down the code, checking out to the branch, and making sure you can get everything to run by following the new README instructions.

```
git fetch
git checkout 9-react
```

### CODE REVIEW

**Comment by leahvelleman** [comment]
It looks like nothing in your readme installs the `react-scripts` command.

```
$ npm run start

> frontend@0.1.0 start /Users/leahvelleman/code/sabelotodo
> react-scripts start

sh: react-scripts: command not found

npm ERR! frontend@0.1.0 start: `react-scripts start`
npm ERR! Exit status 127
npm ERR!
npm ERR! Failed at the frontend@0.1.0 start script.
npm ERR! This is most likely a problem with the frontend package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     react-scripts start
npm ERR! You can get their info via:
npm ERR!     npm owner ls frontend
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 16.7.0
npm ERR! command "node" "/usr/local/bin/npm" "run" "start"
npm ERR! cwd /Users/leahvelleman/code/sabelotodo
npm ERR! node -v v0.10.31
npm ERR! npm -v 1.4.23
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/leahvelleman/code/sabelotodo/npm-debug.log
npm ERR! not ok code 0
```

**Comment by leahvelleman** [comment]
`npm install` is giving an error for me

npm ERR! Error: Method Not Allowed
npm ERR!     at errorResponse (/usr/local/lib/node_modules/npm/lib/cache/add-named.js:260:10)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache/add-named.js:203:12
npm ERR!     at saved (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:167:7)
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 16.7.0
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/leahvelleman/code/sabelotodo
npm ERR! node -v v0.10.31
npm ERR! npm -v 1.4.23
npm ERR! code E405
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/leahvelleman/code/sabelotodo/npm-debug.log
npm ERR! not ok code 0

**Comment by leahvelleman** [comment]
`npm start-prod` does not work for me. Changing to `npm run start-prod` works as described. Should the README be changed, or does my installation have a problem?

**Comment by leahvelleman** [comment]
`npm test` fails for me with error complaining that `fsevents is not a function`. Installing that package explicitly with `npm install fsevents` seems to have solved the problem. Should this dependency be captured somewhere so that it doesn't need to be installed by hand? Or should the requirement to install it by hand be captured in the README?

**Comment by leahvelleman** [comment]
Once `fsevents` is installed, `npm test` shows one failing test. Confirm that this is intentional?

**Comment by raq929** [comment]
Closing to reopen and test that Jest tests run. :crossed_fingers:

**Comment by raq929** [comment]
I'll change the README. 
`fsevents` should be installed via npm install if it's needed, I'll change that.
I didn't bother to change the test when I changed the text on the app (It was a bad test, imho, if that's enough to make it fail, but whatevs.) I'll fix it. Fooling around with CI now.

**Comment by raq929** [comment]
Addressed @leahvelleman's concerns. Merging. (CI still broken)

**Pull request merged**
